# Generated by Django 4.2.30 on 2026-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('landmark', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
